### ISSUE TITLE
Support GHC 9.2

### ISSUE THREAD

**Issue by andreasabel** [Hexirp/doctest-driver-gen#15]
Building on GHC 9.2 works if `base` is bumped
```
$ cabal install doctest-driver-gen --allow-newer=doctest-driver-gen:base
Resolving dependencies...
Build profile: -w ghc-9.2.1 -O1
In order, the following will be built (use -v for more details):
 - doctest-driver-gen-0.3.0.4 (lib) (requires download & build)
 - doctest-driver-gen-0.3.0.4 (exe:doctest-driver-gen) (requires download & build)
```

But the testsuite is blocked on `doctest`:
- [x] sol/doctest#305

**Comment by Hexirp** [comment]
Okay, I'll update it soon.

**Comment by andreasabel** [comment]
I am trying to release doctest for GHC 9.2 very soon, so you can test.
Maybe a revision of doctest-driver-gen on hackage is then sufficient.

**Comment by andreasabel** [comment]
After verifying that with `doctest-0.18.2` the tests work under ghc 9.2.1,
```
$ cabal test --allow-newer=doctest-driver-gen:base 
```
I made the necessary revision on hackage (in my role as hackage trustee):
https://hackage.haskell.org/package/doctest-driver-gen-0.3.0.4/revisions/

There is no urgency now, but you may want to update the repo accordingly.
